- name: Set variables
  set_fact:
    k8s_ingress_release_name: "nginx-ingress"
    k8s_ingress_namespace: "kube-system"

#- name: Check if NGINX ingress is already installed
 # shell: helm status -n 'kube-system' '{{ k8s_ingress_release_name }}'
  #ignore_errors: True
  #register: k8s_ingress_status

#- name: Add stable repo to helm
 # shell: "helm repo add stable https://charts.helm.sh/stable"
 # when: k8s_ingress_status.rc != 0

#- name: Add stable repo to helm
 # shell: "helm repo add nginx-stable https://helm.nginx.com/stable"
  #when: k8s_ingress_status.rc != 0
  
#- name: Update helm repos
 # shell: "helm repo update"
  #when: k8s_ingress_status.rc != 0

#- name: k8s - Install nginx-ingress via helm
 # shell: "helm install --namespace {{ k8s_ingress_namespace }} --set 'controller.extraArgs.default-ssl-certificate=cert-manager/ingress-certificate-secret' --set 'controller.publishService.enabled=true'  '{{ k8s_ingress_release_name }}' 'nginx-stable/nginx-ingress'"
  #when: k8s_ingress_status.rc != 0
