- name: Wait for cloud-init to finish
  raw: while ! test -f /var/lib/cloud/instance/boot-finished; do sleep 1; done
  retries: 20
  delay: 2
  tags:
    - skip_ansible_lint

- name: Setup
  action: setup
